version: '3.1'

services:
  mongodb:
    image: arm64v8/mongo:5.0
    restart: always
    #volumes:
    #  - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root